{% set name = "mpl-point-clicker" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mpl_point_clicker-{{ version }}.tar.gz
  sha256: 91211ac44a9aab38522e435bf1d861c9844bdab2a1f00edd58530ffc940f4a66

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - setuptools >=42
    - setuptools-scm >=6.2
    - pip
  run:
    - python >=3.7
    - matplotlib-base
    - numpy

test:
  imports:
    - mpl_point_clicker
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ianhi/mpl-point-clicker
  license: BSD-3-Clause
  license_file: LICENSE
  summary: A multiclass point clicker for matplotlib

extra:
  recipe-maintainers:
    - ocefpaf
